// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


// nlopt_optimize_fixedv
Rcpp::List nlopt_optimize_fixedv(const Rcpp::List& data, const Rcpp::List& params, const Rcpp::List& config);
RcppExport SEXP _PLNmodels_nlopt_optimize_fixedv(SEXP dataSEXP, SEXP paramsSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimize_fixedv(data, params, config));
    return rcpp_result_gen;
END_RCPP
}
// nlopt_optimize_vestep_fixedv
Rcpp::List nlopt_optimize_vestep_fixedv(const Rcpp::List& data, const Rcpp::List& params, const arma::mat& B, const arma::mat& L, const Rcpp::List& config);
RcppExport SEXP _PLNmodels_nlopt_optimize_vestep_fixedv(SEXP dataSEXP, SEXP paramsSEXP, SEXP BSEXP, SEXP LSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimize_vestep_fixedv(data, params, B, L, config));
    return rcpp_result_gen;
END_RCPP
}
// nlopt_optimize_mstep_fixedv
Rcpp::List nlopt_optimize_mstep_fixedv(const Rcpp::List& data, const Rcpp::List& params, const arma::mat& M, const arma::mat& S, const Rcpp::List& config);
RcppExport SEXP _PLNmodels_nlopt_optimize_mstep_fixedv(SEXP dataSEXP, SEXP paramsSEXP, SEXP MSEXP, SEXP SSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimize_mstep_fixedv(data, params, M, S, config));
    return rcpp_result_gen;
END_RCPP
}
// nlopt_optimize_fixedv_unsup
Rcpp::List nlopt_optimize_fixedv_unsup(const Rcpp::List& data, const Rcpp::List& params, const Rcpp::List& config);
RcppExport SEXP _PLNmodels_nlopt_optimize_fixedv_unsup(SEXP dataSEXP, SEXP paramsSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimize_fixedv_unsup(data, params, config));
    return rcpp_result_gen;
END_RCPP
}
// nlopt_optimize_vestep_fixedv_unsup
Rcpp::List nlopt_optimize_vestep_fixedv_unsup(const Rcpp::List& data, const Rcpp::List& params, const arma::mat& B, const arma::mat& L, const Rcpp::List& config);
RcppExport SEXP _PLNmodels_nlopt_optimize_vestep_fixedv_unsup(SEXP dataSEXP, SEXP paramsSEXP, SEXP BSEXP, SEXP LSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimize_vestep_fixedv_unsup(data, params, B, L, config));
    return rcpp_result_gen;
END_RCPP
}
// nlopt_optimize
Rcpp::List nlopt_optimize(const Rcpp::List& data, const Rcpp::List& params, const Rcpp::List& config);
RcppExport SEXP _PLNmodels_nlopt_optimize(SEXP dataSEXP, SEXP paramsSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimize(data, params, config));
    return rcpp_result_gen;
END_RCPP
}
// nlopt_optimize_vestep
Rcpp::List nlopt_optimize_vestep(const Rcpp::List& data, const Rcpp::List& params, const arma::mat& B, const arma::mat& Omega, const Rcpp::List& config);
RcppExport SEXP _PLNmodels_nlopt_optimize_vestep(SEXP dataSEXP, SEXP paramsSEXP, SEXP BSEXP, SEXP OmegaSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(nlopt_optimize_vestep(data, params, B, Omega, config));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PLNmodels_nlopt_optimize_fixed", (DL_FUNC) &_PLNmodels_nlopt_optimize_fixed, 3},
    {"_PLNmodels_nlopt_optimize_fixedv", (DL_FUNC) &_PLNmodels_nlopt_optimize_fixedv, 3},
    {"_PLNmodels_nlopt_optimize_vestep_fixedv", (DL_FUNC) &_PLNmodels_nlopt_optimize_vestep_fixedv, 5},
    {"_PLNmodels_nlopt_optimize_mstep_fixedv", (DL_FUNC) &_PLNmodels_nlopt_optimize_mstep_fixedv, 5},
    {"_PLNmodels_nlopt_optimize_fixedv_unsup", (DL_FUNC) &_PLNmodels_nlopt_optimize_fixedv_unsup, 3},
    {"_PLNmodels_nlopt_optimize_vestep_fixedv_unsup", (DL_FUNC) &_PLNmodels_nlopt_optimize_vestep_fixedv_unsup, 5},
    {"_PLNmodels_nlopt_optimize", (DL_FUNC) &_PLNmodels_nlopt_optimize, 3},
    {"_PLNmodels_nlopt_optimize_vestep", (DL_FUNC) &_PLNmodels_nlopt_optimize_vestep, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_PLNmodels(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
